updated to use stdbool.h
move.c was failing to build with the following error:

move.c:336:15: error: comparison of constant -1 with expression of type
'bool' is always false
[-Werror,-Wtautological-constant-out-of-range-compare]
        Next = (Next == -1 ? FALSE : TRUE);
                ~~~~ ^  ~~
1 error generated.
*** Error code 1

I added stdbool.h to the mille.h header, changed the case of the
true/falses in the file and replaced the -1 and checks with a less
ambiguous version.